package world.tawa.tawajdbc.dao;

import java.util.List;

/**
 * Created by tawa on 2018-12-16
 */
public abstract class CommonDAO extends BaseDAO{

    public int insert(Object o, boolean returnAutoGeneratedKeys, String... excludeFields){
        beforeInsert();
        return 0;
        //TODO
    }

    public int[] batchInsert(){
        return null;
    }

    public void executeUpdate(){

    }

    public Object queryObject(){
        return null;
    }

    public <T> List<T> queryList(){
        return null;
    }

    public int queryListCount(){
        return 0;
    }

    public void beforeInsert(){

    }
}

